const DATABASE = {
  project: {
    title: "Disability in Western Art",
    subtitle: "A Visual History",
    description: "An online database of artworks depicting disability in Western art history from the medieval period through the early modern era. This research project catalogues 40 significant works across four thematic categories, examining how disability was represented, perceived, and portrayed in visual culture.",
    vrGalleryUrl: "#vr-gallery",
    institution: "Hong Kong Baptist University",
    year: "2026"
  },

  categories: [
    {
      id: "group-1",
      slug: "group-1",
      title: "Healing & Miracles",
      introText: "Works depicting miraculous healing, divine intervention, and medical care of the sick and disabled. These images reflect the intersection of faith, medicine, and disability in early modern religious culture.",
      heroColor: "#8B4513",
      artworkIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    },
    {
      id: "group-2",
      slug: "group-2",
      title: "Social & Civic Life",
      introText: "Representations of disabled people within the social fabric of early modern Europe — as subjects of curiosity, social commentary, and everyday civic participation.",
      heroColor: "#2C5F2E",
      artworkIds: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    },
    {
      id: "group-3",
      slug: "group-3",
      title: "Portraiture & Identity",
      introText: "Formal portraits that document disabled individuals as subjects of dignity, power, or spectacle. These works reflect the complex politics of representation and identity in court and civic portraiture.",
      heroColor: "#1A3A5C",
      artworkIds: [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    },
    {
      id: "group-4",
      slug: "group-4",
      title: "Creative Practice & Disability",
      introText: "Images that explore the relationship between disability and creative practice — artists who created despite or because of impairment, and works that contemplate the senses, the body, and artistic making.",
      heroColor: "#4A1F6B",
      artworkIds: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
    }
  ],

  artworks: [
    {
      id: 1,
      categoryId: "group-1",
      title: "Christ Healing the Blind",
      artist: "El Greco",
      year: "1570",
      location: "Metropolitan Museum, New York",
      url: "https://www.metmuseum.org/art/collection/search/436572",
      shortSummary: "A powerful rendering of the biblical miracle of sight restoration, demonstrating El Greco's distinctive elongated figures and dramatic use of colour.",
      image: "../I/1. El Greco, Christ Healing the Blind, 1570, Metropolitan Museum, New York..jpg",
      tags: ["blindness", "healing", "religious", "miracle"]
    },
    {
      id: 2,
      categoryId: "group-1",
      title: "Miracles of the Black Leg",
      artist: "Fernando del Rincon",
      year: "ca. 1510",
      location: "Museo del Prado, Madrid",
      url: "https://www.museodelprado.es/en/the-collection/art-work/miracles-of-the-doctor-saints-cosmas-and-damian/bfdb052e-4eb4-4aeb-9167-d1e2b247bb8d",
      shortSummary: "Depicts the famous miracle of Saints Cosmas and Damian transplanting a leg, one of the earliest surgical miracle images in Western art.",
      image: "../I/2. Fernando del Rincon, Miracles of the Black Leg. ca. 1510. Museo del Prado, Madrid..jpg",
      tags: ["surgery", "miracle", "saints", "prosthetics"]
    },
    {
      id: 3,
      categoryId: "group-1",
      title: "Care of the Sick",
      artist: "Domenico di Bartolo",
      year: "1440–41",
      location: "Santa Maria della Scala, Siena",
      url: null,
      shortSummary: "A rare secular depiction of hospital care and the treatment of the sick in a civic hospital setting, blending medical and charitable themes.",
      image: "../I/3. Domenico di Bartolo, Care of the Sick. 1440-41. Santa Maria della Scala, Siena..jpg",
      tags: ["hospital", "care", "medicine", "civic"]
    },
    {
      id: 4,
      categoryId: "group-1",
      title: "Christ Healing a Blind Man",
      artist: "Bartholomeus Breenbergh",
      year: "ca. 1635",
      location: "Liechtenstein Princely Collections, Vaduz",
      url: null,
      shortSummary: "A Baroque treatment of the healing miracle set within a classical architectural landscape.",
      image: "../I/4. Bartholomeus Breenbergh, Christ Healing a Blind Man. ca. 1635, Liechtenstein Princely Collections, Vaduz..jpg",
      tags: ["blindness", "healing", "religious", "baroque"]
    },
    {
      id: 5,
      categoryId: "group-1",
      title: "St. Paul Healing the Paralytic at Lystra",
      artist: "Karel Dujardin",
      year: "1663",
      location: "Rijksmuseum, Amsterdam",
      url: null,
      shortSummary: "Depicts the apostolic miracle of physical healing, showing the dynamic contrast between disability and divine cure.",
      image: "../I/5. Karel Dujardin, St. Paul Healing the Paralytic at Lystra. 1663. Rijksmuseum, Amsterdam. .jpg",
      tags: ["paralysis", "healing", "religious", "apostle"]
    },
    {
      id: 6,
      categoryId: "group-1",
      title: "The Infirm at the Pool at Bethesda",
      artist: "Cristoforo de Predis",
      year: "1476",
      location: "Royal Library, Turin",
      url: null,
      shortSummary: "A miniature illustrating the biblical pool of Bethesda, where the disabled gathered hoping for miraculous healing.",
      image: "../I/6. Cristoforo de Predis, The Informs at the Pool at Bethesda. 1476. Royal Library, Turin..jpg",
      tags: ["paralysis", "healing", "biblical", "manuscript"]
    },
    {
      id: 7,
      categoryId: "group-1",
      title: "Christ Heals the Paralytic at the Pool of Bethesda",
      artist: "Bartolome Esteban Murillo",
      year: "1667–1670",
      location: "National Gallery, London",
      url: null,
      shortSummary: "One of the most celebrated Baroque treatments of this biblical theme, notable for its compassionate rendering of the disabled figure.",
      image: "../I/7. Bartolome Esteban Murillo, Christ Heals the Paralytic at the Pool of Bethesda. 1667-1670. National Gallery, London..jpg",
      tags: ["paralysis", "healing", "biblical", "baroque"]
    },
    {
      id: 8,
      categoryId: "group-1",
      title: "St Peter and St John Healing a Cripple at the Gate of the Temple",
      artist: "Albrecht Dürer",
      year: "1513",
      location: "Minneapolis Art Museum, Minneapolis",
      url: "https://collections.artsmia.org/art/47081/st-peter-and-st-john-healing-cripple-at-gate-of-temple-albrecht-duerer",
      shortSummary: "An early print by Dürer depicting apostolic healing, one of his most detailed treatments of a disabled figure.",
      image: "../I/8. Albrecht Dürer, St Peter and St John Healing a Cripple at the Gate of the Temple. 1513. Minneapolis Art Museum, Minneapolis..jpg",
      tags: ["lameness", "healing", "print", "renaissance"]
    },
    {
      id: 9,
      categoryId: "group-1",
      title: "Madonna of the People",
      artist: "Federico Barocci",
      year: "undated",
      location: "Uffizi, Florence",
      url: null,
      shortSummary: "An altarpiece in which disabled and sick figures are shown receiving divine compassion from the Virgin Mary.",
      image: "../I/9. Federico Barocci, Madonna of the People. 157501579. Uffizi, Florence. .jpg",
      tags: ["healing", "religious", "altarpiece", "compassion"]
    },
    {
      id: 10,
      categoryId: "group-1",
      title: "St. Catherine of Siena Exorcising a Possessed Woman",
      artist: "Girolamo di Benvenuto",
      year: "ca. 1505",
      location: "Denver Art Museum, Denver",
      url: null,
      shortSummary: "A painting depicting spiritual healing through exorcism, blurring the boundaries between mental illness and demonic possession in late medieval thought.",
      image: "../I/10. Girolamo di Benvenuto. St. Catherine of Siena Exorcising a Possessed Woman. ca 1505. Denver Art Museum, Denver..png",
      tags: ["possession", "exorcism", "mental illness", "religious"]
    },
    {
      id: 11,
      categoryId: "group-2",
      title: "The Extraction of the Stone of Madness",
      artist: "Hieronymus Bosch",
      year: "ca. 1494",
      location: "Museo del Prado, Madrid",
      url: null,
      shortSummary: "A satirical panel painting depicting a quack surgeon pretending to remove a 'stone of madness' from a patient's head, mocking both medical fraud and human gullibility.",
      image: "../II/1. Hieronymus Bosh, The Extraction of the Stone of Madness. ca 1494. Museo del Prado, Madrid..jpg",
      tags: ["madness", "surgery", "satire", "quackery"]
    },
    {
      id: 12,
      categoryId: "group-2",
      title: "The Blind Leading the Blind",
      artist: "Pieter Brueghel the Elder",
      year: "1568",
      location: "Museo Nazionale di Capodimonte, Naples",
      url: null,
      shortSummary: "Brueghel's masterpiece depicting six blind men in a chain, each inevitably leading the next into a ditch — a moral parable rendered with extraordinary visual specificity.",
      image: "../II/2. Pieter Brueghel the Elder. The Blind Leading the Blind. 1568. Museo Nazionale di Capodimonte, Naples. .jpeg",
      tags: ["blindness", "parable", "social commentary", "renaissance"]
    },
    {
      id: 13,
      categoryId: "group-2",
      title: "The Clubfoot",
      artist: "Jusepe Ribera",
      year: "1642",
      location: "Louvre Museum, Paris",
      url: null,
      shortSummary: "A rare dignified portrait of a begging boy with a clubfoot, shown smiling and holding a paper requesting alms — notable for its humanity and directness.",
      image: "../II/3. Jusepe Ribera, The Clubfoot. 1642. Louvre Museum, Paris. .jpg",
      tags: ["clubfoot", "begging", "poverty", "portraiture"]
    },
    {
      id: 14,
      categoryId: "group-2",
      title: "Plate 94, Rålamb Book of Costumes",
      artist: "Anonymous Artist",
      year: "1657–1658",
      location: "National Library of Sweden, Stockholm",
      url: "https://www.independentliving.org/docs5/mmiles2.html",
      shortSummary: "A costume book illustration depicting a disabled person as part of a broader survey of social types in Ottoman and European society.",
      image: "../II/4. Anonymous Artist, Plate 94. Rålamb Book of Costumes. 1657-1658. National Library of Sweden, Stockholm. .jpg",
      tags: ["costume", "disability", "social types", "manuscript"]
    },
    {
      id: 15,
      categoryId: "group-2",
      title: "A Book Peddler",
      artist: "Master of the Canesso Peddler",
      year: "ca. 1670–1690",
      location: "Metropolitan Museum, New York",
      url: "https://www.metmuseum.org/art/collection/search/910384",
      shortSummary: "A genre painting depicting a disabled street peddler carrying a pack of books, offering a rare glimpse into the working lives of people with disabilities in early modern Europe.",
      image: "../II/5. Master of the Canesso Peddler, A Book Peddler. ca 1670-1690. Metropolitan Museum, New York..jpeg",
      tags: ["peddler", "street life", "working class", "genre painting"]
    },
    {
      id: 16,
      categoryId: "group-2",
      title: "Triple Portrait: Hairy Harry, Mad Peter and Tiny Amon",
      artist: "Agostino Carracci",
      year: "1596–1600",
      location: "Museo Nazionale di Capodimonte, Naples",
      url: null,
      shortSummary: "A triple portrait of court 'curiosities' including hypertrichosis, dwarfism, and apparent intellectual disability, reflecting the early modern fascination with bodily difference.",
      image: "../II/6. Agostino Carracci, Triple Portrait- Hairy Harry, Mad Peter and Tiny Amon. 1596-1600, Museo Nazionale di Capodimonte, Naples..jpg",
      tags: ["court curiosities", "dwarfism", "hypertrichosis", "portraiture"]
    },
    {
      id: 17,
      categoryId: "group-2",
      title: "Portrait of a Hunchback Boy",
      artist: "Annibale Carracci",
      year: "1580s",
      location: "Chatsworth House, Devonshire",
      url: "https://www.chatsworth.org/visit-chatsworth/chatsworth-estate/art-archives/devonshire-collections/old-master-drawings/a-hunchback-boy/",
      shortSummary: "A sympathetic drawing of a hunchback boy, notable for its directness and lack of moralizing, presenting disability as a physical condition rather than a spiritual statement.",
      image: "../II/7. Annibale Carracci, Portrait of a Hunchback Boy. 1580s. Chatsworth House, Devonshire..jpg",
      tags: ["kyphosis", "drawing", "genre", "portraiture"]
    },
    {
      id: 18,
      categoryId: "group-2",
      title: "The Blindness of Tobit",
      artist: "Rembrandt",
      year: "1651",
      location: "Metropolitan Museum, New York",
      url: "https://www.metmuseum.org/art/collection/search/359805",
      shortSummary: "An etching depicting the aged blind Tobit from the Book of Tobit, a subject Rembrandt returned to multiple times throughout his career.",
      image: "../II/8. Rembrandt, The Blindness of Tobit. 1651. Metropolitan Museum, New York.jpeg",
      tags: ["blindness", "old age", "etching", "biblical"]
    },
    {
      id: 19,
      categoryId: "group-2",
      title: "A Street Seller of Shoes",
      artist: "Giuseppe Maria Mitelli",
      year: "1660",
      location: "British Museum, London",
      url: null,
      shortSummary: "A print from a series depicting street trades in Bologna, showing a disabled seller as part of the urban working landscape.",
      image: "../II/9. Giuseppe Maria Mitelli, A Street Seller of Shoes. 1660. British Museum, London..jpg",
      tags: ["street trade", "disability", "print", "urban life"]
    },
    {
      id: 20,
      categoryId: "group-2",
      title: "A Prelingually Deaf Boy in Soisson",
      artist: "Anonymous Artist",
      year: "ca. 1280",
      location: "Real Biblioteca del Monasterio de San Lorenzo de El Escorial, Madrid",
      url: null,
      shortSummary: "A medieval manuscript illumination depicting a deaf boy — one of the earliest known images of deafness as a distinct category of disability in Western art.",
      image: "../II/10. Anonymous Artist, A Prelingually Deaf Boy in Soisson. ca. 1280. Real Biblioteca del Monasterio de San Lorenzo de El Escorial, Madrid..png",
      tags: ["deafness", "medieval", "manuscript", "childhood"]
    },
    {
      id: 21,
      categoryId: "group-3",
      title: "Portrait of Antonietta Gonzalez",
      artist: "Lavinia Fontana",
      year: "1595",
      location: "Château de Blois, Blois",
      url: null,
      shortSummary: "A formal court portrait of Antonietta Gonzalez, who had hypertrichosis, presented with full dignity as a member of the Gonzalez family documented across several courts.",
      image: "../III/1. Lavinia Fontana, Portrait of Antonietta Gonzalez. 1595, Château de Blois, Blois..jpg",
      tags: ["hypertrichosis", "court portrait", "female artist", "identity"]
    },
    {
      id: 22,
      categoryId: "group-3",
      title: "Portrait of Don Diego de Alcedo",
      artist: "Diego Velázquez",
      year: "1645",
      location: "Museo del Prado, Madrid",
      url: "https://www.taylorfrancis.com/chapters/edit/10.4324/9781003048602-8/destierro-desenga%C3%B1o-colin-sanborn",
      shortSummary: "A court portrait of a jester-dwarf, painted with psychological complexity and painterly freedom.",
      image: "../III/2. Diego Velazquez, Portrait of Don Diego de Alcedo. 1545. Museo del Prado, Madrid..jpg",
      tags: ["dwarfism", "court jester", "portraiture", "velazquez"]
    },
    {
      id: 23,
      categoryId: "group-3",
      title: "Portrait of Sebastian de Morra",
      artist: "Diego Velázquez",
      year: "1644",
      location: "Museo del Prado, Madrid",
      url: "https://www.taylorfrancis.com/chapters/edit/10.4324/9781003048602-8/destierro-desenga%C3%B1o-colin-sanborn",
      shortSummary: "One of Velázquez's most celebrated court portraits, depicting a court dwarf with intense directness and psychological depth.",
      image: "../III/3. Diego Velazquez, Portrait of Sebastian de Morra. 1544. Museo del Prado Madrid. .jpg",
      tags: ["dwarfism", "court jester", "portraiture", "velazquez"]
    },
    {
      id: 24,
      categoryId: "group-3",
      title: "Portrait of Baccio di Bartolo (Nano Morgante)",
      artist: "Bronzino",
      year: "1552",
      location: "Pitti Palace, Florence",
      url: "https://www.uffizi.it/en/news/nano-morgante-pittien",
      shortSummary: "A double-sided painted portrait of Nano Morgante, the Medici court dwarf, shown from front and back — a uniquely playful yet complex statement on disability and courtly amusement.",
      image: "../III/4. Bronzino, Portrait of Baccio di Bartolo (Nano Morgante). 1552. Pitti Palace, Florence. .jpg",
      tags: ["dwarfism", "court", "Medici", "portraiture"]
    },
    {
      id: 25,
      categoryId: "group-3",
      title: "The Sense of Touch",
      artist: "Jusepe Ribera",
      year: "1615–1616",
      location: "Norton Simon Museum, Los Angeles",
      url: "https://www.nortonsimon.org/art/detail/F.1965.1.052.P/",
      shortSummary: "From Ribera's series on the Five Senses, depicting touch through an image of blindness — a man examining an object by feel, reflecting the relationship between sensory loss and heightened remaining senses.",
      image: "../III/5. Jusepe Ribera, The Sense of Touch. 1615-1616. Norton Simon Museum, Los Angeles..jpg",
      tags: ["blindness", "senses", "allegory", "touch"]
    },
    {
      id: 26,
      categoryId: "group-3",
      title: "A Woman with no Legs in Elegant Dress on a Table",
      artist: "Giovanni Battista de' Cavalieri",
      year: "1585",
      location: "The British Museum, London",
      url: null,
      shortSummary: "An engraving from a collection of remarkable persons, documenting a woman with limb difference in formal dress.",
      image: "../III/6. Giovanni Battista de’ Cavalieri, A Woman with no Legs in Elegant Dress on a Table. 1585. The British Museum, London. .jpg",
      tags: ["limb difference", "engraving", "identity", "remarkable persons"]
    },
    {
      id: 27,
      categoryId: "group-3",
      title: "Portrait of Queen Henrietta Maria with Sir Jeffrey Hudson",
      artist: "Anthony van Dyck",
      year: "1633",
      location: "National Gallery of Art, Washington",
      url: "https://www.nga.gov/collection/art-object-page.41651.html",
      shortSummary: "A formal royal portrait that includes the famous court dwarf Sir Jeffrey Hudson, whose inclusion complicates notions of status, hierarchy, and disability in court culture.",
      image: "../III/7. Antony van Dyck, Portrait of Queen Henrietta Maria with Sir Jeffrey Hudson. 1633. National Gallery of Art, Washington. .jpg",
      tags: ["dwarfism", "court portrait", "royalty", "van dyck"]
    },
    {
      id: 28,
      categoryId: "group-3",
      title: "Portrait of Eugenia Martinez Vallejo",
      artist: "Juan Carreño de Miranda",
      year: "1680",
      location: "Museo del Prado, Madrid",
      url: "https://www.museodelprado.es/en/the-collection/art-work/eugenia-martinez-vallejo-clothed/f8092cbd-8dd4-4c63-af63-1402940150f0",
      shortSummary: "A striking portrait of Eugenia Martinez Vallejo, known as 'La Monstrua', shown in formal court dress — one of a pair of portraits depicting her clothed and unclothed.",
      image: "../III/8. Juan Carreño de Miranda, Portrait of Eugenia Martinez Vallejo. 1680. Museo del Prado, Madrid..jpg",
      tags: ["obesity", "court portrait", "identity", "female subject"]
    },
    {
      id: 29,
      categoryId: "group-3",
      title: "Portrait of the Dwarf Michol",
      artist: "Juan Carreño de Miranda",
      year: "ca. 1670–82",
      location: "Meadows Museum, Dallas",
      url: "https://www.liebertpub.com/doi/10.1001/archfaci.9.2.152",
      shortSummary: "A court portrait of a dwarf whose identity and condition have been the subject of historical and medical inquiry.",
      image: "../III/9. Juan Carreño de Miranda, Portrait of the Dwarf Michol. ca. 1670-82, Meadows Museum, Dallas..jpeg",
      tags: ["dwarfism", "court portrait", "identity", "Prado"]
    },
    {
      id: 30,
      categoryId: "group-3",
      title: "The Ugly Duchess",
      artist: "Quinten Massys",
      year: "1513",
      location: "National Gallery, London",
      url: "https://news.artnet.com/art-world/ugly-duchess-massys-leonardo-da-vinci-2270566",
      shortSummary: "A satirical portrait traditionally read as a grotesque study of age or physical difference, now reconsidered as potentially depicting a medical condition such as Paget's disease.",
      image: "../III/10. Quinten Massys, The Ugly Duchess. 1513. National Gallery, London. .jpg",
      tags: ["grotesque", "satire", "medical condition", "female subject"]
    },
    {
      id: 31,
      categoryId: "group-4",
      title: "Bequest to Laura Farina",
      artist: "Luca Riva",
      year: "1624",
      location: "Milan State Archive, Milan",
      url: "https://onlinelibrary.wiley.com/doi/full/10.1111/rest.12730",
      shortSummary: "A document accompanied by a visual record of a woman with a disability receiving a bequest — an intersection of legal, economic, and visual history.",
      image: "../IV/1. Luca Riva, Bequest to Laura Farina. 1624. Milan State Archive, Milan. .png",
      tags: ["legal document", "bequest", "disability history", "archive"]
    },
    {
      id: 32,
      categoryId: "group-4",
      title: "The Right Hand",
      artist: "Hendrick Goltzius",
      year: "1588",
      location: "Teylers Museum, Haarlem",
      url: "https://sammlung.staedelmuseum.de/en/work/four-studies-of-a-right-hand",
      shortSummary: "Goltzius, who had a permanently deformed right hand from a childhood accident, made his own hand a subject of meticulous artistic study — an extraordinary act of self-documentation.",
      image: "../IV/2. Hendrick Goltzius, The Right Hand. 1588. Teylers Museum, Haarlem..jpeg",
      tags: ["hand", "disability", "self-portrait", "drawing"]
    },
    {
      id: 33,
      categoryId: "group-4",
      title: "Portrait of a Girl in a Red Dress with a Dog in a Landscape",
      artist: "Jan Jansz",
      year: "ca. 1640",
      location: "Private Collection, UK",
      url: null,
      shortSummary: "A portrait of a young girl that records physical difference within the conventions of formal portraiture.",
      image: "../IV/3. Jan Jansz, Portrait of a Girl in a Red Dress with a Dog in a Landscape. Ca 1640. Private Collection, UK. .jpg",
      tags: ["childhood", "portraiture", "disability", "private collection"]
    },
    {
      id: 34,
      categoryId: "group-4",
      title: "Self-Portrait",
      artist: "Theodorus Steib",
      year: "1651",
      location: "Landesmuseum, Württemberg",
      url: "https://blog.landesmuseum-stuttgart.de/vielseitig-und-selbstbewusst-neuerwerbung-theodor-steibs-selbstbildnis-beim-schreiben-oder-zeichnen/",
      shortSummary: "A self-portrait by an artist born without hands who learned to draw and write with his feet — shown in the act of artistic making, asserting creative identity despite impairment.",
      image: "../IV/4. Theodorus Steib, Self-Portrait. 1651.Landersmuseum, Württemberg..jpg",
      tags: ["self-portrait", "limb difference", "creative practice", "artist"]
    },
    {
      id: 35,
      categoryId: "group-4",
      title: "Male Bust",
      artist: "Giovanni Gonnelli",
      year: "1646",
      location: "Galleria Cesati, Milan",
      url: "https://www.finestresullarte.info/en/works-and-artists/the-extraordinary-story-of-a-blind-sculptor-giovanni-gonnelli-the-blind-man-of-gambassi",
      shortSummary: "A bust by Gonnelli, the 'Blind Man of Gambassi', who became a sculptor after losing his sight — a remarkable example of artistic adaptation.",
      image: "../IV/5. Giovanni Gonnelli, Male Bust. 1646. Galleria Cesati, Milan. .jpg",
      tags: ["blindness", "sculpture", "creative practice", "adaptation"]
    },
    {
      id: 36,
      categoryId: "group-4",
      title: "A Scene on Ice near a Town",
      artist: "Hendrick Avercamp",
      year: "ca. 1615",
      location: "National Gallery, London",
      url: "https://www.nationalgallery.org.uk/paintings/hendrick-avercamp-a-scene-on-the-ice-near-a-town",
      shortSummary: "A winter landscape by Avercamp, who was deaf and mute, representing disability through artistic practice rather than subject matter.",
      image: "../IV/6. Hendrick Avercamp, A Scene on Ice near a Town. ca. 1615, National Gallery, London..jpg",
      tags: ["deafness", "winter landscape", "artist disability", "genre"]
    },
    {
      id: 37,
      categoryId: "group-4",
      title: "Landscapes and Calligraphy",
      artist: "Gao Fenghan",
      year: "1736",
      location: "Metropolitan Museum, New York",
      url: "https://www.metmuseum.org/art/collection/search/49237",
      shortSummary: "Works by the Chinese scholar-painter Gao Fenghan, who continued painting with his non-dominant left hand after paralysis claimed the use of his right hand.",
      image: "../IV/7. Gao Fenghan, Landscapes and Calligraphy. 1736, Metropolitan Museum, New York..jpg",
      tags: ["paralysis", "calligraphy", "adaptation", "Chinese art"]
    },
    {
      id: 38,
      categoryId: "group-4",
      title: "Self-Portrait as a Deaf Man",
      artist: "Joshua Reynolds",
      year: "1775",
      location: "Tate Britain, London",
      url: "https://academic.oup.com/oaj/article/46/3/357/7615843",
      shortSummary: "Reynolds's self-portrait in which he presents himself holding a hand to his ear — a direct acknowledgement of his own progressive deafness.",
      image: "../IV/8. Joshua Reynolds, Self-Portrait as a Deaf man. 1775. Tate Britain, London..jpg",
      tags: ["deafness", "self-portrait", "identity", "artist disability"]
    },
    {
      id: 39,
      categoryId: "group-4",
      title: "Allegory of the Superiority of Painting over Sculpture",
      artist: "Giovanni Francesco Barbieri (Guercino)",
      year: "1635–1640",
      location: "Louvre Museum, Paris",
      url: "https://collections.louvre.fr/en/ark:/53355/cl020003809",
      shortSummary: "A theoretical painting exploring the paragone debate about the relative merits of painting and sculpture — relevant to disability through its engagement with tactile versus visual perception.",
      image: "../IV/9. Giovanni Francesco Barbieri (Guercino), Allegory of the Superiority of Painting over Sculpture. 1635-1640. Louvre Museum, Paris. .png",
      tags: ["paragone", "allegory", "painting vs sculpture", "theory"]
    },
    {
      id: 40,
      categoryId: "group-4",
      title: "The Healing of the Deaf and Mute Boy",
      artist: "Cristoforo de Predis",
      year: "1476",
      location: "Royal Library, Turin",
      url: null,
      shortSummary: "A companion manuscript illumination to Predis's Pool of Bethesda, depicting a miracle that speaks directly to deafness and muteness as categories of disability in biblical narrative.",
      image: "../IV/10. Cristoforo de Predis, The Healing of the Deaf and Mute Boy. 1476. Royal Library, Turin.jpg",
      tags: ["deafness", "muteness", "healing", "manuscript"]
    }
  ]
};

if (typeof module !== 'undefined') module.exports = DATABASE;
